### ISSUE TITLE
tapis executable not in PATH

### ISSUE THREAD

**Issue by JoshuaUrrutia** [TACC-Cloud/tapis-cli#303]
**Describe the bug**
```
pip install --user --local .
```
runs successfully, but the `tapis` command does not get added to the $PATH variable, and it can be hard to find where it got installed (not in the printout after the pip install)

**To Reproduce**
```
docker run --rm -it jurrutia/cli-test:022020
git clone https://github.com/TACC-Cloud/tapis-cli-ng.git
cd tapis-cli-ng
pip3 install --upgrade --user .
tapis --help
```

**Expected behavior**
`tapis` added to the PATH, or print out the location of the install (or both)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS and 
- Ubuntu 16.04.4 LTS (Xenial Xerus)
 

**Additional context**

**Comment by JoshuaUrrutia** [comment]
leaving off the `--user` on the pip install fixes this and installs the executable under:
```
/usr/local/bin/tapis
```

**Comment by mwvaughn** [comment]
This should be resolved for general usage when we move to installing the CLI from `pip`
