### ISSUE TITLE
tapis --help does not list available commands

### ISSUE THREAD

**Issue by eho-tacc** [TACC-Cloud/tapis-cli#309]
**Describe the bug**
`tapis --help` prints "Could not load EntryPoint.parse(...)" instead of available commands.

**To Reproduce**
1. Fresh virtualenv with python 3.6.9 or 3.7.4
2. Clone this repo, cd to repo root, and checkout master
3. Install tapis-cli-ng from source, I've tried the following with python 3.7.4:
`pip install .` (also on 3.6.9)
`pip install --user .` (prohibited in virtualenv, tested in my native Unix env)
`python -m pip install .`
4. Run `tapis --help` in command line. Expect 96 lines of 'Could not load EntryPoint.parse(...)'

**Expected behavior**
`tapis --help` is expected to print list of available commands instead of an error for each command.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Mac OS X 10.15.2
- Python: 3.7.4, 3.6.9
- pip: 20.0.2
- Version: master branch commit 74d3e89ec74f586496d3410e0187a6322d65c162

**Additional context**
N/A

**Comment by mwvaughn** [comment]
This will sort itself out once we are installing solely from pip. It should resolve if you force-uninstall `pip uninstall tapis-cli` then `pip install .`
