### ISSUE TITLE
Windows: Commands failing with Json payload files

### ISSUE THREAD

**Issue by fmckenna** [TACC-Cloud/tapis-cli#338]
**Describe the bug**

have not tried the current code, as i am not a python developer. this bug may have been fixed. i am using that installed through pip install process. if bug has been fixed, someone needs to update the pip package.

tapis-cli does not appear to work on a windows system running through either powershell or the cmd prompt when the application is dealing with a json payload file. Commands that work fine on linux and even windows with the ubuntu system installed, le.g. systems create, apps update, fail with the dreaded python error message "Invalid format string". 

The json files I used work just fine on mac and linux systems (copied with scp). Someone tried on a windows machine with ubuntu subsystem. In ubuntu shell it worked, but same file in same system failed in powershell and terminal. In fact a simple json file with just {} will give the message.

**To Reproduce**

on windows10:

tapis systems create -F file.json

with file.json being correct or even a file with the 2 characters {} will result in error.

**Expected behavior**
It works as it does on mac and linux.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10 Education
 - Version 1903

**Additional context**
this occurred during a workshop with about 20 windows users trying it. no doubt they had different releases of windows10. They also had different flavors of python installed, some from python.org 2.x and 3.x versions and some had active states installation. I myself have windows 10 v 1903 and am running python 3.7.8 from python.org

**Comment by johnfonner** [comment]
Hi @fmckenna,

Thank you for the really nice bug report.  With the update that was just merged, I was able to register systems using Windows PowerShell.  It isn't on PyPI yet, but it will be once the next release happens.  Sorry it took a few weeks to get a fix in for you.

As you discovered, we don't have good testing in place for Windows 10 support without Windows Subsystem for Linux.  Part of our motivation for using a pure Python implementation, though, was to enable the CLI to work on Windows.  Any feedback you have on using the CLI outside of a Linux shell is very welcome.  If you try this again on PowerShell, please let us know what issues you run into.  Also, I am not sure which workshop you were a part of; do you have a link to the material?

Thanks,
John
